on:
  schedule:
    - cron: "0 3 * * *"
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build alpine image
        run: docker build --no-cache src/latest-alpine -t khalyomede/vlang:latest-alpine
      - name: Build Debian image
        run: docker build --no-cache src/latest-debian -t khalyomede/vlang:latest-debian
      - name: Build Ubuntu image
        run: docker build --no-cache src/latest-ubuntu -t khalyomede/vlang:latest-ubuntu
      - name: Push alpine image
        run: docker push khalyomede/vlang:latest-alpine
      - name: Push Debian image
        run: docker push khalyomede/vlang:latest-debian
      - name: Push Ubuntu image
        run: docker push khalyomede/vlang:latest-ubuntu
